-   id: cpp_and_cmake_formatting
    name: Format C++ and CMake code
    entry: scripts/format.py
    language: python
    args: [ "--no-write", "CMakeLists.txt", "submodules/CMakeLists.txt", "external/CMakeLists.txt", "--directory", "src", "--directory", "cmake", "--directory", "tests" ]
