# Config file for https://pre-commit.com/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/pre-commit
    rev: v2.17.0
    hooks:
      - id: validate_manifest
  - repo: local
    hooks:
      - id: cpp_and_cmake_formatting
        name: Format C++ and CMake code
        entry: scripts/format.py
        language: python
        args: [ "--no-write", "src" ]
