function(add_files)
  cmake_parse_arguments(PARAM "" "TARGET" "CONDITIONAL" ${ARGN})
  set(PARAM_FILES "${PARAM_UNPARSED_ARGUMENTS}")
  foreach(FILE IN LISTS PARAM_FILES)
    target_sources(${PARAM_TARGET} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/${FILE}")
  endforeach()
endfunction()
